name: Build and publish azure-cli image

on:

  push:
    branches:
      - master
    paths:
      - 'azure-cli/*'
      - '.github/workflows/azure-cli-docker-image.yaml'

env:
  DOCKER_IMAGE: paulbouwer/azure-cli

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch versions
      run: |
        echo ::set-env name=AZURECLI_VERSION::$(cat azure-cli/versions.json | jq -r ".azurecli")
        echo ::set-env name=KUBECTL_VERSION::$(cat azure-cli/versions.json | jq -r ".kubectl")
        echo ::set-env name=HELM_VERSION::$(cat azure-cli/versions.json | jq -r ".helm")

    - name: Build image
      run: |
        docker build -t $DOCKER_IMAGE:$AZURECLI_VERSION \
          --build-arg AZURECLI_VERSION="$AZURECLI_VERSION" \
          --build-arg KUBECTL_VERSION="$KUBECTL_VERSION" \
          --build-arg HELM_VERSION="$HELM_VERSION" \
          --file ./azure-cli/Dockerfile ./azure-cli

    - name: Log into registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to registry
      run: |
        docker push $DOCKER_IMAGE:$AZURECLI_VERSION

