name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch release version
      run: |
        azurecli_version=$(curl -sL https://api.github.com/repos/Azure/azure-cli/releases/latest |  jq -r ".tag_name" | sed -e 's/azure-cli-//g') \
        && cat versions.json | jq ".azurecli=\"$azurecli_version\"" > tmp && mv tmp versions.json
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
